<?php

namespace SWCombine\SDK\Web;

class RouteTypes {
    const CHARACTER = 'character/';
    const INVENTORY = 'inventory/';
    const EVENTS = 'events/';
    const FACTION = 'faction/';
    const CITIES = 'galaxy/cities/';
    const PLANETS = 'galaxy/planets/';
    const SECTORS = 'galaxy/sectors/';
    const STATIONS = 'galaxy/stations/';
    const SYSTEMS = 'galaxy/systems/';
    const INDEX = '/';
    const GNS = 'news/gns/';
    const AUTOGNS = 'news/gns/auto/';
    const ECONOMY = 'news/gns/economy/';
    const ARTICLE = 'news/gnsitem/';
    const MILITARY = 'news/gns/military/';
    const POLITICAL = 'news/gns/political/';
    const SOCIAL = 'news/gns/social/';
    const SIMNEWS = 'news/simnews/';
    const COMMUNITY = 'news/simnews/community/';
    const PLAYER = 'news/simnews/player/';
    const TECHNICAL = 'news/simnews/technical/';
    const CLASSES = 'types/classes/';
    const TYPES = 'types/';
    const ENTITYTYPES = 'types/entitytypes/';
    const FACTIONTYPES = 'types/factions/';
}
